name: adv_camera_example
version: 1.0.0+1
description: Demonstrates how to use the adv_camera plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  characters: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  adv_camera:
    path: ../

flutter:
  uses-material-design: true